#!/usr/bin/env Rscript

# Command-line tool to plot multiple CLIP tracks with gene structures
# A. M. Chakrabarti
# C. Capitanchik
#
# The code is in the clipplotr R package (R/). When this script is run from a
# clone of the repository it loads R/ directly, so the package does not need to
# be installed; otherwise it uses the installed package.
# Run ./clipplotr --help for all options.

args <- commandArgs(trailingOnly = FALSE)
script <- sub("^--file=", "", args[grep("^--file=", args)])
repo_dir <- dirname(normalizePath(script))

if(file.exists(file.path(repo_dir, "DESCRIPTION")) && dir.exists(file.path(repo_dir, "R"))) {

  for(package in c("GenomeInfoDb", "rtracklayer", "GenomicFeatures", "AnnotationDbi", "ggplot2", "cowplot", "ggthemes", "patchwork", "data.table")) {
    suppressPackageStartupMessages(library(package, character.only = TRUE))
  }

  clipplotr <- new.env()
  for(f in sort(list.files(file.path(repo_dir, "R"), pattern = "\\.R$", full.names = TRUE))) sys.source(f, envir = clipplotr)
  clipplotr$run_cli(commandArgs(trailingOnly = TRUE))

} else {

  clipplotr::run_cli(commandArgs(trailingOnly = TRUE))

}
