# You can use this file to create a conda environment for clipplotr:
# conda env create -f environment.yml

name: clipplotr

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - conda-forge::r-base=4.0.3
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-ggplot2=3.3.3
  - conda-forge::r-scales=1.1.1
  - conda-forge::r-ggthemes=4.2.4
  - conda-forge::r-cowplot=1.1.1
  - conda-forge::r-patchwork=1.1.1
  - conda-forge::r-smoother=1.1
  - conda-forge::r-zoo=1.8
  - conda-forge::r-data.table=1.14.0

  - bioconda::bioconductor-rtracklayer=1.50.0
  - bioconda::bioconductor-genomicfeatures=1.42.2